apiVersion: v1
kind: Service
metadata:
  name: {{ include "lagoon-logging.logsDispatcher.fullname" . }}
  labels:
    {{- include "lagoon-logging.logsDispatcher.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    {{- include "lagoon-logging.logsDispatcher.selectorLabels" . | nindent 4 }}
  ports:
  - name: forward
    port: 24224
    protocol: TCP
    targetPort: 24224
  - name: metrics
    port: 24231
    protocol: TCP
    targetPort: 24231
  - name: applicationlog
    port: 5140
    protocol: UDP
    targetPort: 5140
  - name: syslog
    port: 5141
    protocol: UDP
    targetPort: 5141
