apiVersion: v1
entries:
  lagoon-remote:
  - apiVersion: v2
    appVersion: 1.4.0
    created: "2020-02-11T15:45:40.108798-06:00"
    description: A Helm chart to run a lagoon-remote
    digest: 15d7e20d6fe611b119beeb9abbd7cccc062101e3eac4149d7f903916f54376cd
    name: lagoon-remote
    type: application
    urls:
    - lagoon-remote-0.1.2.tgz
    version: 0.1.2
generated: "2020-02-11T15:45:40.107264-06:00"
