apiVersion: v1
kind: Service
metadata:
  name: {{ include "rabbitmq.fullname" . }}
  labels:
    {{- include "rabbitmq.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.httpApi.port }}
      targetPort: 15672
      protocol: TCP
      name: tcp-15672
    - port: {{ .Values.service.amqp.port }}
      targetPort: 5672
      protocol: TCP
      name: tcp-5672
  selector:
    {{- include "rabbitmq.selectorLabels" . | nindent 4 }}
