apiVersion: v1
entries:
  lagoon-remote:
  - apiVersion: v2
    appVersion: 1.4.0
    created: "2020-02-09T20:51:47.547268-06:00"
    description: A Helm chart to run a lagoon-remote
    digest: 0cf4b4b5dd08e7bcb74239ef729ef516384f3b733249d75cfe7ac6246de9ec51
    name: lagoon-remote
    type: application
    urls:
    - lagoon-remote-0.1.1.tgz
    version: 0.1.1
generated: "2020-02-09T20:51:47.543795-06:00"
