version: '2.3'

x-lagoon-project:
  &lagoon-project lagoon-remote

services:
  logs-forwarder-logstash:
    build:
      context: logs-forwarder-logstash
      dockerfile: Dockerfile
    labels:
      lagoon.type: custom
      lagoon.template: logs-forwarder-logstash/.lagoon.yml
  logs-forwarder:
    build:
      context: logs-forwarder
      dockerfile: Dockerfile
    labels:
      lagoon.type: custom
      lagoon.template: logs-forwarder.remote.yml # logs-forwarder in a remote openshift needs a special config
  logs-collector:
    image: openshift/origin-logging-fluentd:v3.6.1
    labels:
      lagoon.type: custom
      lagoon.rollout: daemonset
      lagoon.template: logs-collector/.lagoon.yml
  docker-host:
    image: amazeeio/docker-host:latest
    labels:
      lagoon.type: custom
      lagoon.template: docker-host/docker-host.yaml
  broker:
    image: amazeeio/rabbitmq-cluster:v1.1.4
    ports:
      - '15672:15672'
      - '5672:5672'
    labels:
      lagoon.type: rabbitmq-cluster
      lagoon.template: services/broker/.lagoon.app.yml
      lagoon.image: amazeeiolagoon/broker:v1-1-4
